#
# CSE183 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /authenticate:
    post:
      description: Checks User
      requestBody:
        description: User to Check
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserReq'
      responses:
        200:
          description: User exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authenticated'
        403:
          description: Username or password incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ua:
    get:
      description: Gets user account JSON from specified email
      parameters:
        - name: email
          in: query
          description: email of user
          schema:
            type: string
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAccount'
        404:
          description: UserAccount Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /channelschat:
    get:
      description: Gets channels from specified queries
      parameters:
        - name: ws
          in: query
          description: workspace
          schema:
            type: string
        - name: cn
          in: query
          description: channel name
          schema:
            type: string
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatLog'
        404:
          description: ChatLog Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Posts to channel from specified info
      requestBody:
        description: info of stuff for adding
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserReqChannels'
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatObj'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /dmschat:
    get:
      description: Gets chatlog from specified dms queries
      parameters:
        - name: id
          in: query
          description: id of user
          schema:
            type: string
        - name: idWith
          in: query
          description: id of with user
          schema:
            type: string
        - name: ws
          in: query
          description: workspace name
          schema:
            type: string
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatLog'
        404:
          description: ChatLog Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Posts to dms from specified info
      requestBody:
        description: info of stuff for adding
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserReqDms'
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatObj'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /dmdusers:
    get:
      description: Gets user info of users Dmd with
      parameters:
        - name: id
          in: query
          description: id of user
          schema:
            type: string
        - name: ws
          in: query
          description: workspace name
          schema:
            type: string
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersInfo'
        404:
          description: Uhh Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /channelslist:
    get:
      description: Gets list of channels from specified query
      parameters:
        - name: ws
          in: query
          description: current workspace
          schema:
            type: string
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsList'
        404:
          description: ChannelsList Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Adds a new channel to the current workspace
      parameters:
        - name: ws
          in: query
          description: current workspace
          schema:
            type: string
        - name: cn
          in: query
          description: channel name to add
          schema:
            type: string
      responses:
        201:
          description: Succesful
        400:
          description: Bad Request


  /workspaceslist:
    get:
      description: Gets list of workspaces from specified query
      parameters:
        - name: ident
          in: query
          description: ident of current user
          schema:
            type: string
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspacesList'
        404:
          description: WorkspacesObj Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    DummyResponse:
      required:
        - message
      properties:
        message:
          type: string

    Authenticated:
      type: object
      properties:
        name:
          type: string
        accessToken:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
        workspaces:
           type: array
           items:
             $ref: '#/components/schemas/workspaceName'

    UserAccount:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        password:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
        workspaces:
           type: array
           items:
             $ref: '#/components/schemas/workspaceName'

    ChatLog:
      type: array
      items:
        $ref: '#/components/schemas/ChatObj'

    ChatObj:
      type: object
      properties:
        date:
          type: string
          format: date-time
        from:
          type: string
        content:
          type: string
        senderID:
          type: integer

    UsersInfo:
      type: array
      items:
        $ref: '#/components/schemas/UserObj'

    UserObj:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    ChannelsList:
      type: array
      items:
        $ref: '#/components/schemas/channelName'

    channelName:
      type: string

    WorkspacesList:
      type: array
      items:
        $ref: '#/components/schemas/workspaceName'

    workspaceName:
      type: string

    UserReq:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - password
        - email

    UserReqChannels:
      type: object
      properties:
        id:
          type: integer
        ws:
          type: string
        cn:
          type: string
        content:
          type: string
      required:
        - id
        - ws
        - cn
        - content

    UserReqDms:
      type: object
      properties:
        id:
          type: integer
        idWith:
          type: integer
        ws:
          type: string
        content:
          type: string
      required:
        - id
        - ifWith
        - ws
        - content

    User:
      required:
        - password
        - email
      properties:
        password:
          type: string
        email:
          type: string
          format: email
      additionalProperties: false

# AUTHORIZATION COMPONENTS
#  securitySchemes:
 #   bearerAuth:            # arbitrary name for the security scheme
 #     type: http
 #     scheme: bearer
  #    bearerFormat: JWT    # optional, arbitrary value for documentation purposes

# Authorization - based on Professor's Books Auth
# security:
#  - bearerAuth: []         # use the same name as above